Update design area references to CAF docs
Azure/aca-landing-zone-accelerator pull request #128
Opened 2023-12-18 23:13 UTC by aarthiem

2023-12-19 12:54 UTC, thotheod requested changes

2023-12-19 12:54 UTC, thotheod commented on README.md
> +- [Identity and Access Management](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/app-platform/container-apps/identity)
can we remove **/en-us**/ from the URLs?

2024-01-17 15:44 UTC, aarthiem commented on README.md
> +- [Identity and Access Management](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/app-platform/container-apps/identity)
@thotheod removed the /en-us

2024-02-25 19:28 UTC, thotheod approved these changes

2024-02-25 19:28 UTC, merged