Included Workload Profile, UDR and Azure Firewall into Terraform implementation
Azure/aca-landing-zone-accelerator pull request #132
Opened 2024-01-15 07:28 UTC by HoussemDellai

**Changes in this PR:**

- Created Azure Firewall module for SKU Basic
- Created Firewall Policy with rules to allow egress traffic for needed resources
- Created Route Table attached to infra subnet to route all traffic to Firewall
- Created Workload Profile in ACA Environment
- Changed infra subnet CIDR range to /27 (just to demo this is possible)
- Added Diagnostic Settings for Firewall
- Added naming convention for Firewall and Firewall Policy

**Tested and working:**

- Tested the egress traffic from ACA App go through Azure Firewall public IP (`curl ifconf.me`)

**Tested and not working:**
- Redeployed the same template multiple times, and it breaks because of dependencies between modules (noticed this same behavior with the main branch).
- Also noticed that Terraform starts creating Diagnostic Settings (DS), then for some reason stops immediately. DS is then created but Terraform is not aware about the creation, so it is not saved into the state file. On next execution, I notice a conflict.

2024-01-29 21:58 UTC, ibersanoMS requested changes
Great work here! Thanks for the contribution. Had a few comments around making sure properties are controlled by variables, workload profile is still optional and ensuring the new modules are consistent with the existing Bicep implementation. Once you've made those updates, I'll do a test deployment, verify everything looks good and approve. Thanks!

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/aca-internal/terraform/modules/01-hub/variables.tf
> +# variable "firewallPolicyRuleCollectionGroups" {
Remove commented out code if not being used

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/aca-internal/terraform/modules/05-hello-world-sample-app/main.tf
> +  workload_profile_name        = "profile-D4"
This needs to be controlled by a variable

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/aca-internal/terraform/outputs.tf
> +// Hub
Why was this commented out?

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/aca-internal/terraform/providers.tf
> +  # uncomment if you want to save state file into remote storae account
This needs to be uncommented as we direct people to use Azure Storage for TF state

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/aca-internal/terraform/tfplan
Remove

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/shared/terraform/modules/aca-environment/main.tf
> +    name                  = "profile-D4"
All four properties: name, workload profile type, max count and min count need to be controlled by variables

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/shared/terraform/modules/aca-environment/main.tf
> +  workload_profile {
Defining this here makes it a required field. We need a way for this to be optional. Since it can only be defined inline, the workload profile def should use dynamic and take in an array of workload profile names so that if the array is empty, it can deploy the environment without it.

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/shared/terraform/modules/diagnostics/main.tf
> +      # retention_policy has been deprecated in favor of azurerm_storage_management_policy
Remove

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/shared/terraform/modules/diagnostics/main.tf
> +      # retention_policy has been deprecated in favor of azurerm_storage_management_policy
Remove

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/shared/terraform/modules/firewall/main.tf
> +  # for_each = var.firewallPolicyRuleCollectionGroups
Remove commented out code

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/shared/terraform/modules/firewall/main.tf
> +  sku_name            = "AZFW_VNet" # AZFW_Hub
Needs to be controlled by variable

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/shared/terraform/modules/firewall/main.tf
> +  sku_tier            = "Basic"     # "Standard"  # Premium  # "Basic" #
Needs to be controlled by variable

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/shared/terraform/modules/firewall/main.tf
> +  zones               = ["1"] # ["1", "2", "3"]
Needs to be controlled by variable

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/shared/terraform/modules/firewall/main.tf
> +  sku                 = "Basic" # "Standard" # "Premium" #
Needs to be controlled by variable

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/shared/terraform/modules/firewall/provider.tf
Remove

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/shared/terraform/modules/networking/route-table/variables.tf
These variables either need default values or need to be required

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/shared/terraform/modules/networking/vnet/main.tf
> +        # name    = lookup(delegation.value, "service_name")
Remove commented out code

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/shared/terraform/modules/networking/route-table/main.tf
Check for parity with Bicep module

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/shared/terraform/modules/firewall/main.tf
Check for parity with Bicep module

2024-01-29 21:58 UTC, ibersanoMS commented on scenarios/aca-internal/terraform/terraform.tfvars
> +clientIP                            = "176.177.25.47"
Remove clientIP and replace with previous placeholder

2024-02-05 21:59 UTC, HoussemDellai commented on scenarios/shared/terraform/modules/firewall/provider.tf
Removed provider.tf empty file from all modules. A terraform module should not have provider.

2024-02-06 09:26 UTC, HoussemDellai commented
@ibersanoMS done :) You can re-check !

2024-02-06 22:12 UTC, ibersanoMS requested changes
If you can just fix the IP, I'll approve and we can get this merged! Thanks!

2024-02-06 22:12 UTC, ibersanoMS commented on scenarios/aca-internal/terraform/terraform.tfvars
> +clientIP                            = "176.177.25.47" # "<Add your client IP here for use in KeyVault access permissions>"
Remove your IP and put just the place holder in quotations. We don't want to expose your public IP address in the main branch.

2024-02-07 06:37 UTC, HoussemDellai commented
@ibersanoMS done :)

2024-02-07 14:32 UTC, ibersanoMS approved these changes

2024-02-07 15:44 UTC, thotheod approved these changes
Look Great! Thanks!

2024-02-07 15:44 UTC, merged